### ISSUE TITLE
casting breaks the highlighting

### ISSUE THREAD

**Issue by DerZyklop** [deankevorkian/language-typescript-react#2]
See:

![screen shot 2018-10-25 at 19 09 24](https://user-images.githubusercontent.com/912344/47517850-b692e700-d889-11e8-82fe-b87b908ab215.png)

**Comment by deankevorkian** [comment]
Hey! sorry for the delay on this, guess I missed it. I updated the README. This is no longer maintained as there's no point of holding it (since the changes I've made to the upstream are already there).
Sorry!
